### PR TITLE
Total migration redo

### PR DESCRIPTION
**Pull request by iMattPro**
This is more like how the migrations should have be written.

Of course, I've had to rewrite existing migrations, which means if anybody ever installed this...they can't update..they will have to completely uninstall the extension, and reinstall it fresh again. Hopefully you never made this publicly available to anyone. Because I just don't see how one can come back from the original migrations that were here.

This is how your migrations should have been handled to update old MOD installations, and handle new installations as well.

You can use this, learn from this or whatever. But as I said, this is what you'd need to be doing if you want to submit this to CDB. At the same time, these changes assume nobody except the developers have ever installed this extension.

The main mistake in the very first migration was you can not implement DB changes via the effectively installed function. You must use the normal update data and schema methods only. This PR shows how all the changes could have been accomplished this way.

### CODE REVIEW

**Comment by MarkDHamill** [comment]
Matt, this is quite a bit of labor and certainly worthy of study. Thank you. I have been looking at your Pages extension as you suggested. In general I have been following the Acme demo and the Wiki. You have developed what looks to me like a set of best practices for handling versioning, upgrading, etc. If this is the recommendation of the phpBB group it would be helpful if the Wiki were updated accordingly.

I am in the middle of making changes based on the review, but undoubtedly I have been slowed by the migration logic and trying to make it backward compatible with the mod. I've had the effectively_installed issue addressed for a couple of weeks now since the review came back (it took four months). I am using PHP Storm now which certainly helps in finding unused variables and such.

The forum is great for asking questions. I am thinking asking for a peer review before submitting would be helpful.

Sorry for being such a Luddite. The move from 3.0 to 3.1 was a big leap for me, as I am a casual programmer. Things were much simpler when I was writing a mod.

**Review by MarkDHamill — APPROVED** [review]

**Comment by MarkDHamill** [comment]
Thanks so much Matt for taking the time to parse through all this, clean it up and use best practices.

**Comment by 3D-I** [comment]
problems to be faced now:
1 - your extension has been publicly made available and those users will need a stand-alone script to get rid of your old migrations. I don't see any other way, as VSE said.
2 - the ext has been submitted and denied, now it's up to the extension team (especially Paul) to decide what to do about the new migrations.
3 - you merged this commit but I am seeing some lines that shouldn't be there, as a matter of fact VSE didn't commit those.. ( see some example but there are more of this )..

https://github.com/MarkDHamill/digests/blob/beaa91b0744d58122ce149ed14130d835e0c3320/ext.php#L22
https://github.com/MarkDHamill/digests/blob/beaa91b0744d58122ce149ed14130d835e0c3320/ext.php#L308
https://github.com/MarkDHamill/digests/blob/beaa91b0744d58122ce149ed14130d835e0c3320/ext.php#L313

something went wrong there while merging IMO.

**Comment by iMattPro** [comment]
As I said, this hasn't really been released yet. In theory the only people who should have used it are those testing it out. Anybody who has previously installed it will need to fully uninstall and reinstall fresh. Nobody can update from a prior version of this extension. And that needs to be made clear. Anybody irresponsible enough to have gone and used an unreleased extension in development on a live site is up a creek for such behavior. They too will have to completely remove and reinstall. That's the price of installing undeveloped software.

**Comment by iMattPro** [comment]
@3D-I what you're seeing is what happens when you don't fix merge conflicts.

**Comment by MarkDHamill** [comment]
The merge conflicts are fixed. I integrated some code changes that I was working on when VSE's code came in. The extension installs and removes fine on 3.1.10 now. I am still having issues when upgrading from phpBB 3.0.14 with a version 2.2.27 of the digests mod installed, mainly it sees two UCP_DIGEST category modules in the modules table, which does not seem to be correct but that's what the error message says. Anyhow, it stops the installer. I can provide a copy of that database prior to installing the extension if anyone is interested.

**Pull request merged**
