### PR TITLE
Update common.php and info_acp_common.php

### PR DESCRIPTION
**Pull request by Praggle**
Indentation corrected and one or two changes in translation

### CODE REVIEW

**Comment by MarkDHamill** [comment]
Thanks Praggle for the contributions.

**Comment by Praggle** [comment]
Did you see, that there was also an update of info_acp_common.php that could be merged? You can look into Fork, but I don't know, what has to be done to merge it. Maybe I missed to create a socond pull request.

**Comment by MarkDHamill** [comment]
It's possible I missed it. Post it on the forum and I will merge it.

**Comment by Praggle** [comment]
I think, it is already here in your Github-Repository. You just have to merge it: to 
see here:
[Fork](https://github.com/MarkDHamill/digests/network) -> The green branch should be merged.
or directly
[here](https://github.com/Praggle/digests/commit/241e9e38ddfd98437f6d852739d01dbc4aebd4de)
Or do I have to open a second pull request? I'll have a look.

**Pull request merged**
